package gofr

import (
	"context"
	"fmt"
	"net/http"
	"net/http/httptest"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"go.opentelemetry.io/otel/trace"

	"gofr.dev/pkg/gofr/container"
	"gofr.dev/pkg/gofr/logging"
)

// recordedLog is a single call captured by recordingLogger.
type recordedLog struct {
	method string
	format string
	args   []any
}

// recordingLogger captures every call so tests can assert which logger received
// a message and which arguments (including the trace ID marker) were passed.
type recordingLogger struct {
	logs  []recordedLog
	level logging.Level
}

func (r *recordingLogger) recordf(method, format string, args ...any) {
	r.logs = append(r.logs, recordedLog{method: method, format: format, args: args})
}

func (r *recordingLogger) Debug(args ...any)             { r.recordf("Debug", "", args...) }
func (r *recordingLogger) Debugf(f string, args ...any)  { r.recordf("Debugf", f, args...) }
func (r *recordingLogger) Log(args ...any)               { r.recordf("Log", "", args...) }
func (r *recordingLogger) Logf(f string, args ...any)    { r.recordf("Logf", f, args...) }
func (r *recordingLogger) Info(args ...any)              { r.recordf("Info", "", args...) }
func (r *recordingLogger) Infof(f string, args ...any)   { r.recordf("Infof", f, args...) }
func (r *recordingLogger) Notice(args ...any)            { r.recordf("Notice", "", args...) }
func (r *recordingLogger) Noticef(f string, args ...any) { r.recordf("Noticef", f, args...) }
func (r *recordingLogger) Warn(args ...any)              { r.recordf("Warn", "", args...) }
func (r *recordingLogger) Warnf(f string, args ...any)   { r.recordf("Warnf", f, args...) }
func (r *recordingLogger) Error(args ...any)             { r.recordf("Error", "", args...) }
func (r *recordingLogger) Errorf(f string, args ...any)  { r.recordf("Errorf", f, args...) }
func (r *recordingLogger) Fatal(args ...any)             { r.recordf("Fatal", "", args...) }
func (r *recordingLogger) Fatalf(f string, args ...any)  { r.recordf("Fatalf", f, args...) }
func (r *recordingLogger) ChangeLevel(level logging.Level) {
	r.level = level
	r.recordf("ChangeLevel", "")
}

func tracedTestContext() (ctx context.Context, traceID string) {
	sc := trace.NewSpanContext(trace.SpanContextConfig{
		TraceID:    trace.TraceID{0x0a, 0x0b, 0x0c, 0x0d, 0x0e, 0x0f, 0x10, 0x11, 0x12, 0x13, 0x14, 0x15, 0x16, 0x17, 0x18, 0x19},
		SpanID:     trace.SpanID{0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07, 0x08},
		TraceFlags: trace.FlagsSampled,
	})

	return trace.ContextWithSpanContext(context.Background(), sc), sc.TraceID().String()
}

// countTraceMarkers counts the args that render as the given trace ID; the marker
// type is unexported in the logging package, so it is matched by its value.
func countTraceMarkers(args []any, traceID string) int {
	n := 0

	for _, a := range args {
		if fmt.Sprint(a) == traceID {
			n++
		}
	}

	return n
}

// callAllLogMethods invokes every logging.Logger method once on ctx.
func callAllLogMethods(ctx *Context) {
	ctx.Debug("m")
	ctx.Debugf("m %s", "a")
	ctx.Log("m")
	ctx.Logf("m %s", "a")
	ctx.Info("m")
	ctx.Infof("m %s", "a")
	ctx.Notice("m")
	ctx.Noticef("m %s", "a")
	ctx.Warn("m")
	ctx.Warnf("m %s", "a")
	ctx.Error("m")
	ctx.Errorf("m %s", "a")
	ctx.Fatal("m")
	ctx.Fatalf("m %s", "a")
}

func allLogMethods() []string {
	return []string{
		"Debug", "Debugf", "Log", "Logf", "Info", "Infof", "Notice", "Noticef",
		"Warn", "Warnf", "Error", "Errorf", "Fatal", "Fatalf",
	}
}

func methodsOf(logs []recordedLog) []string {
	out := make([]string, 0, len(logs))
	for _, l := range logs {
		out = append(out, l.method)
	}

	return out
}

// Hand-built contexts (tests, background jobs, gofr-cli generated gRPC wrappers)
// leave ContextLogger zero-valued. Logging through the context must fall back to
// the container's logger instead of dereferencing a nil base logger.
func TestContext_Logging_HandBuiltContextFallsBackToContainerLogger(t *testing.T) {
	tracedCtx, traceID := tracedTestContext()

	tests := []struct {
		desc        string
		stdCtx      context.Context
		wantMarkers int
	}{
		{desc: "background context logs without a trace marker", stdCtx: context.Background(), wantMarkers: 0},
		{desc: "traced context keeps the trace ID", stdCtx: tracedCtx, wantMarkers: 1},
		{desc: "nil context logs without a trace marker", stdCtx: nil, wantMarkers: 0},
	}

	for _, tc := range tests {
		t.Run(tc.desc, func(t *testing.T) {
			rec := &recordingLogger{}
			ctx := &Context{Context: tc.stdCtx, Container: &container.Container{Logger: rec}}

			require.NotPanics(t, func() { callAllLogMethods(ctx) })

			require.Equal(t, allLogMethods(), methodsOf(rec.logs))

			for _, l := range rec.logs {
				assert.Equal(t, tc.wantMarkers, countTraceMarkers(l.args, traceID), "method %s", l.method)
			}
		})
	}
}

// The gRPC wrapper generated by gofr-cli builds the context with exactly these
// fields; ctx.Errorf in a gRPC handler must not panic.
func TestContext_Logging_GRPCWrapperShapedContext(t *testing.T) {
	tracedCtx, traceID := tracedTestContext()
	rec := &recordingLogger{}

	ctx := &Context{
		Context:   tracedCtx,
		Container: &container.Container{Logger: rec},
		Request:   nil,
	}

	require.NotPanics(t, func() { ctx.Errorf("failed: %v", "boom") })
	require.Len(t, rec.logs, 1)
	assert.Equal(t, "Errorf", rec.logs[0].method)
	assert.Equal(t, "failed: %v", rec.logs[0].format)
	assert.Equal(t, 1, countTraceMarkers(rec.logs[0].args, traceID))
}

// Framework-built contexts must keep logging through their ContextLogger: one
// trace marker per call, delivered to the logger the ContextLogger wraps.
func TestContext_Logging_FrameworkContextUsesContextLogger(t *testing.T) {
	tracedCtx, traceID := tracedTestContext()

	containerLog := &recordingLogger{}
	ctxLog := &recordingLogger{}

	ctx := &Context{
		Context:       tracedCtx,
		Container:     &container.Container{Logger: containerLog},
		ContextLogger: logging.ContextLoggerFor(tracedCtx, ctxLog),
	}

	callAllLogMethods(ctx)

	assert.Empty(t, containerLog.logs, "an initialized ContextLogger must not be bypassed")
	require.Equal(t, allLogMethods(), methodsOf(ctxLog.logs))

	for _, l := range ctxLog.logs {
		assert.Equal(t, 1, countTraceMarkers(l.args, traceID), "method %s", l.method)
	}
}

func TestContext_Logging_NewHTTPContextKeepsSingleTraceMarker(t *testing.T) {
	tracedCtx, traceID := tracedTestContext()
	rec := &recordingLogger{}

	req := httptest.NewRequestWithContext(tracedCtx, http.MethodGet, "/", http.NoBody)
	ctx := newHTTPContext(httptest.NewRecorder(), req, &container.Container{Logger: rec})

	ctx.Infof("hello %s", "world")

	require.Len(t, rec.logs, 1)
	assert.Equal(t, 1, countTraceMarkers(rec.logs[0].args, traceID))
}

func TestContext_ChangeLevel(t *testing.T) {
	t.Run("hand-built context changes the container logger level", func(t *testing.T) {
		rec := &recordingLogger{}
		ctx := &Context{Context: context.Background(), Container: &container.Container{Logger: rec}}

		require.NotPanics(t, func() { ctx.ChangeLevel(logging.WARN) })
		assert.Equal(t, logging.WARN, rec.level)
	})

	t.Run("framework context changes the wrapped logger level", func(t *testing.T) {
		rec := &recordingLogger{}
		ctx := newContext(nil, &noopRequest{}, &container.Container{Logger: rec})

		ctx.ChangeLevel(logging.ERROR)
		assert.Equal(t, logging.ERROR, rec.level)
	})
}

func TestContext_ImplementsLogger(*testing.T) {
	var _ logging.Logger = (*Context)(nil)
}

type discardLogger struct{}

func (discardLogger) Debug(...any)              {}
func (discardLogger) Debugf(string, ...any)     {}
func (discardLogger) Log(...any)                {}
func (discardLogger) Logf(string, ...any)       {}
func (discardLogger) Info(...any)               {}
func (discardLogger) Infof(string, ...any)      {}
func (discardLogger) Notice(...any)             {}
func (discardLogger) Noticef(string, ...any)    {}
func (discardLogger) Warn(...any)               {}
func (discardLogger) Warnf(string, ...any)      {}
func (discardLogger) Error(...any)              {}
func (discardLogger) Errorf(string, ...any)     {}
func (discardLogger) Fatal(...any)              {}
func (discardLogger) Fatalf(string, ...any)     {}
func (discardLogger) ChangeLevel(logging.Level) {}

func BenchmarkContext_Infof(b *testing.B) {
	tracedCtx, _ := tracedTestContext()
	req := httptest.NewRequestWithContext(tracedCtx, http.MethodGet, "/", http.NoBody)
	c := &container.Container{Logger: discardLogger{}}

	b.Run("framework context", func(b *testing.B) {
		ctx := newHTTPContext(httptest.NewRecorder(), req, c)

		b.ReportAllocs()

		for b.Loop() {
			ctx.Infof("hello %s", "world")
		}
	})

	b.Run("hand-built context", func(b *testing.B) {
		ctx := &Context{Context: tracedCtx, Container: c}

		b.ReportAllocs()

		for b.Loop() {
			ctx.Infof("hello %s", "world")
		}
	})
}
