[default]
locale = "en-us"
extend-ignore-re=[
	# UID and equivalent
	"[A-Za-z0-9=_-]{30,}",

]

# List of words that are ignored
# Please add a comment about why they are ignored
[default.extend-words]
#ba = "ba"       		# short variable name
datas = "datas" 		# common errors on datum/data plural, but too many to fix
mosquitto = "mosquitto" # this is a MQQT broker
IIT = "IIT" 			# Indian Institute of Technology

[files]
# excluded file
extend-exclude = [
	"go.sum","go.mod", # go.sum and go.mod contains URLs with hash, they can provide false positive
	"vendor",          # not my dragon
	"pkg/gofr/static/swagger*",
	]
