[default]
locale = "en-us"
extend-ignore-re=[
	# UID and equivalent
	"[A-Za-z0-9=_-]{30,}",

	# False positive managements with inline comments
	#
	# disable spellchecker for current line with a comment mentioning "spellchecker:disable-line"
	"(?Rm)^.*(<!--|#|//)\\s*spellchecker:disable-line(-->|\n)?$",
	# disable a block from a "spellchecker:on" comment to "spellchecker:off" one
  	"(?s)(<!--|#|//)\\s*spellchecker:off\\s*([^-\n]*-->|[^\n]*\n).*?(<!--|#|//)\\s*spellchecker:on",
]

# List of words that are ignored
# Please add a comment about why they are ignored
[default.extend-words]
#ba = "ba"       		# short variable name
datas = "datas" 		# common errors on datum/data plural, but too many to fix
mosquitto = "mosquitto" # this is a MQQT broker
IIT = "IIT" 			# Indian Institute of Technology
# WARNING: Before adding new words here
# Consider false-positive managements with inline comments as mentioned above

[files]
# excluded file
extend-exclude = [
	"go.sum","go.mod", # go.sum and go.mod contains URLs with hash, they can provide false positive
	"vendor",          # not my dragon
	"pkg/gofr/static/swagger*",
	]
