{
 "title": "Gofr Redis Cache Metrics",
 "refresh": "5s",
 "panels": [
  {
   "title": "Cache Hits",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "gofr_redis_cache_hits_total", "legendFormat": "{{cache_name}}" }
   ]
  },
  {
   "title": "Cache Misses",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "gofr_redis_cache_misses_total", "legendFormat": "{{cache_name}}" }
   ]
  },
  {
   "title": "Cache Sets",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "gofr_redis_cache_sets_total", "legendFormat": "{{cache_name}}" }
   ]
  },
  {
   "title": "Cache Deletes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    { "expr": "gofr_redis_cache_deletes_total", "legendFormat": "{{cache_name}}" }
   ]
  },
  {
   "title": "Current Item Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    { "expr": "gofr_redis_cache_items_current", "legendFormat": "{{cache_name}}" }
   ]
  }
 ]
}