// Code generated by MockGen. DO NOT EDIT.
// Source: interface.go

// Package eventhub is a generated GoMock package.
package eventhub

import (
	reflect "reflect"

	aad "github.com/Azure/azure-amqp-common-go/v3/aad"
	gomock "github.com/golang/mock/gomock"
)

// MockAzureAadJWTProvider is a mock of AzureAadJWTProvider interface.
type MockAzureAadJWTProvider struct {
	ctrl     *gomock.Controller
	recorder *MockAzureAadJWTProviderMockRecorder
}

// MockAzureAadJWTProviderMockRecorder is the mock recorder for MockAzureAadJWTProvider.
type MockAzureAadJWTProviderMockRecorder struct {
	mock *MockAzureAadJWTProvider
}

// NewMockAzureAadJWTProvider creates a new mock instance.
func NewMockAzureAadJWTProvider(ctrl *gomock.Controller) *MockAzureAadJWTProvider {
	mock := &MockAzureAadJWTProvider{ctrl: ctrl}
	mock.recorder = &MockAzureAadJWTProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAzureAadJWTProvider) EXPECT() *MockAzureAadJWTProviderMockRecorder {
	return m.recorder
}

// NewJWTProvider mocks base method.
func (m *MockAzureAadJWTProvider) NewJWTProvider(c *Config) (*aad.TokenProvider, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewJWTProvider", c)
	ret0, _ := ret[0].(*aad.TokenProvider)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NewJWTProvider indicates an expected call of NewJWTProvider.
func (mr *MockAzureAadJWTProviderMockRecorder) NewJWTProvider(c interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewJWTProvider", reflect.TypeOf((*MockAzureAadJWTProvider)(nil).NewJWTProvider), c)
}
