// Code generated by MockGen. DO NOT EDIT.
// Source: interfaces.go
//
// Generated by this command:
//
//	mockgen -source=interfaces.go -destination=mock_interfaces.go -package=cassandra
//

// Package cassandra is a generated GoMock package.
package cassandra

import (
	reflect "reflect"

	gocql "github.com/gocql/gocql"
	gomock "go.uber.org/mock/gomock"
)

// MockclusterConfig is a mock of clusterConfig interface.
type MockclusterConfig struct {
	ctrl     *gomock.Controller
	recorder *MockclusterConfigMockRecorder
}

// MockclusterConfigMockRecorder is the mock recorder for MockclusterConfig.
type MockclusterConfigMockRecorder struct {
	mock *MockclusterConfig
}

// NewMockclusterConfig creates a new mock instance.
func NewMockclusterConfig(ctrl *gomock.Controller) *MockclusterConfig {
	mock := &MockclusterConfig{ctrl: ctrl}
	mock.recorder = &MockclusterConfigMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockclusterConfig) EXPECT() *MockclusterConfigMockRecorder {
	return m.recorder
}

// CreateSession mocks base method.
func (m *MockclusterConfig) CreateSession() (session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSession")
	ret0, _ := ret[0].(session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateSession indicates an expected call of CreateSession.
func (mr *MockclusterConfigMockRecorder) CreateSession() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSession", reflect.TypeOf((*MockclusterConfig)(nil).CreateSession))
}

// Mocksession is a mock of session interface.
type Mocksession struct {
	ctrl     *gomock.Controller
	recorder *MocksessionMockRecorder
}

// MocksessionMockRecorder is the mock recorder for Mocksession.
type MocksessionMockRecorder struct {
	mock *Mocksession
}

// NewMocksession creates a new mock instance.
func NewMocksession(ctrl *gomock.Controller) *Mocksession {
	mock := &Mocksession{ctrl: ctrl}
	mock.recorder = &MocksessionMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mocksession) EXPECT() *MocksessionMockRecorder {
	return m.recorder
}

// Query mocks base method.
func (m *Mocksession) Query(stmt string, values ...any) query {
	m.ctrl.T.Helper()
	varargs := []any{stmt}
	for _, a := range values {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Query", varargs...)
	ret0, _ := ret[0].(query)
	return ret0
}

// Query indicates an expected call of Query.
func (mr *MocksessionMockRecorder) Query(stmt any, values ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{stmt}, values...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Query", reflect.TypeOf((*Mocksession)(nil).Query), varargs...)
}

// Mockquery is a mock of query interface.
type Mockquery struct {
	ctrl     *gomock.Controller
	recorder *MockqueryMockRecorder
}

// MockqueryMockRecorder is the mock recorder for Mockquery.
type MockqueryMockRecorder struct {
	mock *Mockquery
}

// NewMockquery creates a new mock instance.
func NewMockquery(ctrl *gomock.Controller) *Mockquery {
	mock := &Mockquery{ctrl: ctrl}
	mock.recorder = &MockqueryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mockquery) EXPECT() *MockqueryMockRecorder {
	return m.recorder
}

// Exec mocks base method.
func (m *Mockquery) Exec() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Exec")
	ret0, _ := ret[0].(error)
	return ret0
}

// Exec indicates an expected call of Exec.
func (mr *MockqueryMockRecorder) Exec() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Exec", reflect.TypeOf((*Mockquery)(nil).Exec))
}

// Iter mocks base method.
func (m *Mockquery) Iter() iterator {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Iter")
	ret0, _ := ret[0].(iterator)
	return ret0
}

// Iter indicates an expected call of Iter.
func (mr *MockqueryMockRecorder) Iter() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Iter", reflect.TypeOf((*Mockquery)(nil).Iter))
}

// MapScanCAS mocks base method.
func (m *Mockquery) MapScanCAS(dest map[string]any) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MapScanCAS", dest)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MapScanCAS indicates an expected call of MapScanCAS.
func (mr *MockqueryMockRecorder) MapScanCAS(dest any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MapScanCAS", reflect.TypeOf((*Mockquery)(nil).MapScanCAS), dest)
}

// Mockiterator is a mock of iterator interface.
type Mockiterator struct {
	ctrl     *gomock.Controller
	recorder *MockiteratorMockRecorder
}

// MockiteratorMockRecorder is the mock recorder for Mockiterator.
type MockiteratorMockRecorder struct {
	mock *Mockiterator
}

// NewMockiterator creates a new mock instance.
func NewMockiterator(ctrl *gomock.Controller) *Mockiterator {
	mock := &Mockiterator{ctrl: ctrl}
	mock.recorder = &MockiteratorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mockiterator) EXPECT() *MockiteratorMockRecorder {
	return m.recorder
}

// Columns mocks base method.
func (m *Mockiterator) Columns() []gocql.ColumnInfo {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Columns")
	ret0, _ := ret[0].([]gocql.ColumnInfo)
	return ret0
}

// Columns indicates an expected call of Columns.
func (mr *MockiteratorMockRecorder) Columns() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Columns", reflect.TypeOf((*Mockiterator)(nil).Columns))
}

// NumRows mocks base method.
func (m *Mockiterator) NumRows() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NumRows")
	ret0, _ := ret[0].(int)
	return ret0
}

// NumRows indicates an expected call of NumRows.
func (mr *MockiteratorMockRecorder) NumRows() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NumRows", reflect.TypeOf((*Mockiterator)(nil).NumRows))
}

// Scan mocks base method.
func (m *Mockiterator) Scan(dest ...any) bool {
	m.ctrl.T.Helper()
	varargs := []any{}
	for _, a := range dest {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Scan", varargs...)
	ret0, _ := ret[0].(bool)
	return ret0
}

// Scan indicates an expected call of Scan.
func (mr *MockiteratorMockRecorder) Scan(dest ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Scan", reflect.TypeOf((*Mockiterator)(nil).Scan), dest...)
}
