FROM grafana/grafana:latest

# Expose Grafana's default port
EXPOSE 3000

# Optionally, you can add provisioning for dashboards and datasources here
# COPY provisioning /etc/grafana/provisioning

# Start Grafana
CMD ["/run.sh"] 